let arrUsuarios=[];

const user1={
    nombre: "Alan",
    rol: "Admin"
};

const user2={
    nombre: "Valentin",
    rol: "Admin"
}

arrUsuarios.push(user1);
arrUsuarios.push(user2);

console.log(arrUsuarios);

//LOCAL STORAGE
//ALMACENA DE LA SIGUIENTE MANERA --> KEY-VALOR (STRING-STRING)
//LA KEY ES EL NOMBRE QUE LE ASIGNAMOS Y EL VALOR ES EL VALOR PORPIAMENTE DICHO
//TIENE DOS METODOS

//SET ITEM --> ES PARA CREAR NUEVO REGISTRO
//GET ITEM --> ES PARA OBTENER UN REGISTRO

//GUARDAR UN REGISTRO EN LOCAL STORAGE LS

localStorage.setItem("TEST","PROBANDO EL ALMACENANMIENTO EN EL LOCAL STORAGE")
//KEY = "TEST"
//VALOR = "PROBANDO EL ALMACENAMIENTO EN EL LOCAL STORAGE"


//OBTENER UN REGISTRO DEL LOCAL STORAGE LS
//MUESTRA EL VALOR, LA KEY ES PARA IDENTIFICARLO

console.log(localStorage.getItem("TEST"));

//MODIFICAR EL VALOR DE UN REGISTROS YA CREADO

localStorage.setItem("TEST", "PROBANDO LA MODIFICACION");
console.log(localStorage.getItem("TEST"));

//ELIMINAR UN REGISTRO DEL LS

localStorage.removeItem("TEST");

localStorage.setItem("TEST","PROBANDO EL ALMACENANMIENTO EN EL LOCAL STORAGE")
localStorage.setItem("TEST2","PROBANDO EL ALMACENANMIENTO EN EL LOCAL STORAGE")
localStorage.setItem("TEST3","PROBANDO EL ALMACENANMIENTO EN EL LOCAL STORAGE")

localStorage.clear() //BORRA TODO...

//JSON Javascript objets notation
//NOS PROPORCIONA DOS METODOS 
//1- PARA TRANSFORMAR UN OBJETO O ARRAY EN STRING
//2-PARA HACER EL STRING EN OBJETO O ARRAY 

//CONVERTIR EL ARRAY DE OBJETOS EN UN STRING PARA PODER GUARDAR EN EL LOCAL STORAGE

localStorage.setItem("usuarios", JSON.stringify(arrUsuarios));

//DE ESTA MANERA LO VOLVEMOS AL ESTADO ORIGINAL, EN ESTE CASO LO VOLVEMOS A TRANSFORMAR EN UN ARRAY DE OBJETOS
const user = JSON.parse(localStorage.getItem("usuarios")) //USUARIOS ES LA KEY

console.log(user);

